# Generated by Django 5.0.4 on 2024-04-16 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chain", "0002_alter_cattle_process_location_and_more"),
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="continent",
        ),
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="cities_light.city"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="cities_light.country"
            ),
        ),
    ]
